### ISSUE TITLE
Project restructure proposal

### ISSUE THREAD

**Issue by chkoar** [western-greece-developers/meetup#28]
I propose the following structure for the project.
 
meetups (folder)
README.MD (file)
PROPOSALS.MD (file)
HISTORY.MD (file)

### meetups 
This folder will contain sub-folders which will be named using 3 characters integer e.g. 001 (for better sorting). In each sub-folder there will be probably a folder named *presentations* and a README.md file related to the event.

### README.MD
General information

### PROPOSALS.MD
Here we will have in one place the proposals for talks and/or workshops. So we will get rid of the files like [this](https://github.com/western-greece-developers/meetup/blob/master/meetups/13/README.md)

### HISTORY.MD
Here we will have a sort overview about what happened in past meetups. So, we could quick see the topics of the past meetups along with the presenters without going back and forth. This file could be unnecessary and merge the information at the bottom of PROPOSALS.MD like [here](https://github.com/western-greece-developers/meetup/blob/master/meetups/13/README.md)

What do you think?

**Comment by jimmykarily** [comment]
Sounds good. Should we migrate all past meetups to the new structure?

**Comment by chkoar** [comment]
Well, if it is fast yes. Otherwise we could just rename the directories to 3 chars and ajust the three files in the root.

**Comment by chkoar** [comment]
Since everyone (I hope so) has github account we could mention the nicknames in proposals.  For instance, instead of this:
>A quick introduction of Python 3.7 data classes (chkoar/pychristos)
We should have this:
A quick introduction of Python 3.7 data classes (@chkoar)

**Comment by chkoar** [comment]
Ι made a draft (or a final) in #29
